# Generated by Django 3.1.6 on 2021-04-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuery',
            new_name='Userinfo',
        ),
    ]
